# Generated by Django 4.2 on 2023-07-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('time_created',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'ordering': ('time_created',), 'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзинах'},
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая стоимость'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='several_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена за количество'),
        ),
    ]
