# Generated by Django 4.2 on 2023-07-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_options_alter_cartproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='several_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за количество'),
        ),
    ]
